Repository UMC-MindStone/FrontEnd, pull requests merged in 2025-01, with the labels that each got.

#5 [#4] Chore: 컬러 업데이트
  app/src/main/res/values/colors.xml
Labels: CHORE🧹, 이안🦊

#10 [#6] Feat : 회원가입 화면 및 기능
  .idea/.gitignore
  .idea/deploymentTargetSelector.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/other.xml
  .idea/vcs.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mindstone/SignupCodeActivity.kt
  app/src/main/java/com/example/mindstone/SignupEmailActivity.kt
  app/src/main/java/com/example/mindstone/SignupPasswordActivity.kt
  app/src/main/res/colors/menu_selector_color.xml
  app/src/main/res/drawable/btn_back.xml
  app/src/main/res/drawable/btn_disabled.xml
  app/src/main/res/drawable/btn_pink_background.xml
  app/src/main/res/drawable/btn_toggle_eye.xml
  app/src/main/res/drawable/btn_transparent_background.xml
  app/src/main/res/drawable/ic_emailerror.xml
  app/src/main/res/layout/activity_signup_code.xml
  app/src/main/res/layout/activity_signup_email.xml
  app/src/main/res/layout/activity_signup_password.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/style.xml
Labels: UI📱

#12 [#9] Feat: 회원가입 이용 약관 화면 및 기능 구현
  .idea/.name
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mindstone/CompleteActivity.kt
  app/src/main/java/com/example/mindstone/PrivacyFragment.kt
  app/src/main/java/com/example/mindstone/ServiceActivity.kt
  app/src/main/java/com/example/mindstone/TermFragment.kt
  app/src/main/res/drawable/bnt_checked_normal.xml
  app/src/main/res/drawable/btn_checked_selected.xml
  app/src/main/res/drawable/btn_login_normal.xml
  app/src/main/res/drawable/ic_agree.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_checkmark.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_complete.xml
  app/src/main/res/drawable/ic_go.xml
  app/src/main/res/drawable/ic_line.xml
  app/src/main/res/drawable/ic_nextbutton.xml
  app/src/main/res/drawable/ic_personal.xml
  app/src/main/res/drawable/ic_register.xml
  app/src/main/res/drawable/ic_termofuse.xml
  app/src/main/res/layout/activity_complete.xml
  app/src/main/res/layout/activity_service.xml
  app/src/main/res/layout/fragment_privacy.xml
  app/src/main/res/layout/fragment_term.xml
  app/src/main/res/values/strings.xml
Labels: UI📱

#14 [#13] Feat: 로그인 후 닉네임 설정 화면 구현
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mindstone/AfterLoginActivity.kt
  app/src/main/java/com/example/mindstone/MakeNicknameActivity.kt
  app/src/main/res/drawable/ic_calm.xml
  app/src/main/res/drawable/ic_hello.xml
  app/src/main/res/layout/activity_after_login.xml
  app/src/main/res/layout/activity_make_nickname.xml
Labels: UI📱

#23 [#15] Feat: 일기 화면 및 기능 구현
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/deploymentTargetSelector.xml
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/migrations.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/src/main/java/com/example/mindstone/BeforeDiaryFragment.kt
  app/src/main/java/com/example/mindstone/DiaryEditFragment.kt
  app/src/main/java/com/example/mindstone/DiaryHomeFragment.kt
  app/src/main/java/com/example/mindstone/DiaryImgFragment.kt
  app/src/main/java/com/example/mindstone/DiaryLoadingFragment.kt
  app/src/main/java/com/example/mindstone/DiaryViewModel.kt
  app/src/main/java/com/example/mindstone/HomeQuestionFragment.kt
  app/src/main/java/com/example/mindstone/HomeQuestionFragment1.kt
  app/src/main/java/com/example/mindstone/NotiRVAdapter.kt
  app/src/main/java/com/example/mindstone/NotificationFragment.kt
  app/src/main/java/com/example/mindstone/TodayFinishFragment.kt
  app/src/main/res/drawable/background_textfield.xml
  app/src/main/res/drawable/btn_autocreate_able.xml
  app/src/main/res/drawable/btn_autocreate_disabled.xml
  app/src/main/res/drawable/btn_completed.xml
  app/src/main/res/drawable/btn_down.xml
  app/src/main/res/drawable/btn_notification.xml
  app/src/main/res/drawable/btn_write.xml
  app/src/main/res/drawable/ic_blank_diary.png
  app/src/main/res/drawable/ic_character.xml
  app/src/main/res/drawable/ic_diary_box.png
  app/src/main/res/drawable/ic_diary_edit_box.png
  app/src/main/res/drawable/ic_edittext.xml
  app/src/main/res/drawable/ic_fitimage.png
  app/src/main/res/drawable/ic_gallery.xml
  app/src/main/res/drawable/ic_left_balloon.png
  app/src/main/res/drawable/ic_loading_star.xml
  app/src/main/res/drawable/ic_pen.xml
  app/src/main/res/drawable/ic_question_box.png
  app/src/main/res/drawable/ic_questionmark.xml
  app/src/main/res/drawable/ic_refresh.xml
  app/src/main/res/drawable/ic_right_balloon.png
  app/src/main/res/drawable/ic_status_bar.png
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_before_diary.xml
  app/src/main/res/layout/fragment_diary_edit.xml
  app/src/main/res/layout/fragment_diary_home.xml
  app/src/main/res/layout/fragment_diary_img.xml
  app/src/main/res/layout/fragment_diary_loading.xml
  app/src/main/res/layout/fragment_home_question.xml
  app/src/main/res/layout/fragment_home_question1.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/fragment_today_finish.xml
  app/src/main/res/layout/item_notification.xml
  app/src/main/res/values/colors.xml
  gradle/libs.versions.toml
Labels: FEAT✨, UI📱

#27 [#21] Feat : 습관 달력 및 습관 관리 화면 구현
  app/src/main/java/com/example/mindstone/ColorPickerFragment.kt
  app/src/main/java/com/example/mindstone/EmotionCalendarGridAdapter.kt
  app/src/main/java/com/example/mindstone/HabitCalendarFragment.kt
  app/src/main/java/com/example/mindstone/HabitCalendarGridAdapter.kt
  app/src/main/java/com/example/mindstone/HabitCheckFragment.kt
  app/src/main/java/com/example/mindstone/HabitReportFragment.kt
  app/src/main/java/com/example/mindstone/TimePickerFragment.kt
  app/src/main/res/drawable/background_habit_progressbar.xml
  app/src/main/res/drawable/background_radius_black.xml
  app/src/main/res/drawable/btn_graph_normal.xml
  app/src/main/res/drawable/btn_gray_circle.xml
  app/src/main/res/drawable/btn_green_circle.xml
  app/src/main/res/drawable/btn_nothing_normal.xml
  app/src/main/res/drawable/btn_pink_circle.xml
  app/src/main/res/drawable/btn_purple_circle.xml
  app/src/main/res/drawable/btn_red_circle.xml
  app/src/main/res/drawable/btn_skyblue_circle.xml
  app/src/main/res/drawable/btn_yellow_circle.xml
  app/src/main/res/drawable/habit_progressbar.xml
  app/src/main/res/drawable/ic_black_ring.xml
  app/src/main/res/drawable/ic_progressbar.xml
  app/src/main/res/drawable/ic_text_bubble.xml
  app/src/main/res/layout/fragment_color_picker.xml
  app/src/main/res/layout/fragment_emotion_calendar.xml
  app/src/main/res/layout/fragment_habit_calendar.xml
  app/src/main/res/layout/fragment_habit_check.xml
  app/src/main/res/layout/fragment_habit_report.xml
  app/src/main/res/layout/fragment_time_picker.xml
  app/src/main/res/layout/frame_habit_check.xml
  app/src/main/res/layout/grid_emotion_item.xml
  app/src/main/res/layout/grid_habit_item.xml
  app/src/main/res/values/dimens.xml
Labels: UI📱

#29 [#24] 회원가입 api 연결
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mindstone/RetrofitClient.kt
  app/src/main/java/com/example/mindstone/ServiceActivity.kt
  app/src/main/java/com/example/mindstone/SignupCodeActivity.kt
  app/src/main/java/com/example/mindstone/signup/SignupCodeActivity.kt
  app/src/main/java/com/example/mindstone/signup/SignupEmailActivity.kt
  app/src/main/java/com/example/mindstone/signup/SignupPasswordActivity.kt
  app/src/main/java/com/example/mindstone/signup/SignupPayload.kt
  app/src/main/java/com/example/mindstone/signup/SignupViewModel.kt
  app/src/main/res/layout/activity_signup_code.xml
  app/src/main/res/layout/activity_signup_email.xml
  app/src/main/res/layout/activity_signup_password.xml
  app/src/main/res/xml/network_security_config.xml
Labels: FEAT✨

#33 [#32] Feat: 로그인, 이메일 찾기 api 연결
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mindstone/MyApplication.kt
  app/src/main/java/com/example/mindstone/data/local/PreferenceManager.kt
  app/src/main/java/com/example/mindstone/data/remote/AuthService.kt
  app/src/main/java/com/example/mindstone/data/remote/LoginService.kt
  app/src/main/java/com/example/mindstone/data/remote/RetrofitClient.kt
  app/src/main/java/com/example/mindstone/data/repository/FindEmailRepositoryImpl.kt
  app/src/main/java/com/example/mindstone/domain/entity/FindEmailRequest.kt
  app/src/main/java/com/example/mindstone/domain/entity/FindEmailResponse.kt
  app/src/main/java/com/example/mindstone/domain/entity/LoginRequest.kt
  app/src/main/java/com/example/mindstone/domain/entity/LoginResponse.kt
  app/src/main/java/com/example/mindstone/domain/repository/FindEmailRepository.kt
  app/src/main/java/com/example/mindstone/domain/usecase/FindEmailUseCase.kt
  app/src/main/java/com/example/mindstone/ui/auth/login/FindEmailFragment.kt
  app/src/main/java/com/example/mindstone/ui/auth/login/FindEmailViewModel.kt
  app/src/main/java/com/example/mindstone/ui/auth/login/LoginActivity.kt
  app/src/main/java/com/example/mindstone/ui/auth/login/LoginViewModel.kt
  app/src/main/java/com/example/mindstone/util/LoginDialogUtil.kt
  app/src/main/res/layout/activity_signup_email.xml
  app/src/main/res/layout/activity_signup_password.xml
Labels: FEAT✨
